### PR TITLE
Network request await

### PR DESCRIPTION
**Pull request by clayrab**

### CODE REVIEW

**Comment by escapedcat** [comment]
fyi, instead of writing i.e. WIP you can use the official `Draft` functionality from GH:  
image
Did this juts now

**Comment by escapedcat** [comment]
such 💚

**Comment by clayrab** [comment]
David merged this into main and pushed it directly without a PR... closing.

**Comment by trevelyan** [comment]
Technically it was this PR. If anyone prefers handling the merge another
way, please go ahead.

merge_clay_networking_code
<https://github.com/SaitoTech/saito-rust/tree/merge_clay_networking_code>

**Pull request merged**
